services:
  db:
    image: postgres:15
    container_name: cocos_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./src/db/test-database.sql:/docker-entrypoint-initdb.d/test-database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tester -d cocos_test"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    
  api:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"